FROM ruby:2.5

ENV APP_PORT=8080

ENV APP_USERNAME=sinhook
ENV APP_PASSWORD=sinhook
ENV APP_BASIC_AUTH=true
ENV ENCRYPTED_YAML false

ENV HOOKS_TO_STORE=50
ENV HOOKS_STORAGE=folder
ENV HOOKS_FOLDER_STORAGE_PATH="/data/"
ENV RACK_ENV production

WORKDIR /app

COPY ./ /app
RUN gem install sinatra rerun
RUN bundle install
RUN mkdir $HOOKS_FOLDER_STORAGE_PATH

ENTRYPOINT ["sh", "./scripts/launch" ]
EXPOSE $APP_PORT
